server:
    port: 9000

spring:
    application:
        name: ecommerce
    cloud:
        config:
            enabled: false
    security:
        oauth2:
            client:
                provider:
                    keycloak-provider:
                        issuer-uri: http://localhost:8083/auth/realms/ecommerce
                registration:
                    keycloak-spring-gateway-client:
                        provider: keycloak-provider
                        client-id: ecommerce-ui-client
                        authorization-grant-type: authorization_code
                        redirect-uri: '{baseUrl}/login/oauth2/code/keycloak'