server:
    port: 8080

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

spring:
    application:
        name: gateway
    cloud:
        gateway:
            routes:
                -   id: products
                    uri: lb://products
                    predicates:
                        - Path=/products/**

                -   id: brands
                    uri: lb://products
                    predicates:
                        - Path=/brands/**

                -   id: users
                    uri: lb://users
                    predicates:
                        - Path=/users/**
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: http://localhost:8083/auth/realms/ecommerce/protocol/openid-connect/certs

logging:
    level:
        org:
            springframework: DEBUG