server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: products
          uri: lb://products
          predicates:
            - Path=/products/**

        - id: users
          uri: lb://users
          predicates:
            - Path=/users/**

logging:
  level:
    org.springframework.cloud.gateway: debug